### ISSUE TITLE
不能添加在my-staging.json里预置的验证人之外的验证人

### ISSUE THREAD

**Issue by differs** [kaichaosun/substrate-stencil#1]
![2021-03-08 12-27-54 的屏幕截图](https://user-images.githubusercontent.com/16659721/110378997-20e7f480-800b-11eb-8794-a074d4c6bd96.png)
![2021-03-08 12-24-01 的屏幕截图](https://user-images.githubusercontent.com/16659721/110379006-234a4e80-800b-11eb-83c5-c6092ee6be15.png)

希望大神能指导一下

**Comment by kaichaosun** [comment]
需要使用substrate的3.0或者master，这个仓库的更新比较慢。
