### ISSUE TITLE
no method named `as_fd` found for struct `Async` in the current scope

### ISSUE THREAD

**Issue by blox-venture** [kaichaosun/substrate-stencil#14]
I'm unable to build the master branch on macOS. 

> `error[E0599]: no method named `as_fd` found for struct `Async` in the current scope
>    --> /Users/usamaali/.cargo/registry/src/github.com-1ecc6299db9ec823/async-process-1.5.0/src/lib.rs:514:16
>     |
> 514 |         self.0.as_fd()
>     |                ^^^^^ method not found in `Async<std::process::ChildStdin>`
> 
> error[E0271]: type mismatch resolving `<OwnedFd as TryFrom<Async<std::process::ChildStdin>>>::Error == std::io::Error`
>    --> /Users/usamaali/.cargo/registry/src/github.com-1ecc6299db9ec823/async-process-1.5.0/src/lib.rs:523:17
>     |
> 523 |         value.0.try_into()
>     |                 ^^^^^^^^ expected enum `Infallible`, found struct `std::io::Error`
> 
> error[E0277]: the trait bound `OwnedFd: From<Async<std::process::ChildStdin>>` is not satisfied
>    --> /Users/usamaali/.cargo/registry/src/github.com-1ecc6299db9ec823/async-process-1.5.0/src/lib.rs:523:17
>     |
> 523 |         value.0.try_into()
>     |                 ^^^^^^^^ the trait `From<Async<std::process::ChildStdin>>` is not implemented for `OwnedFd`
>     |
>     = help: the following other types implement trait `From<T>`:
>               <OwnedFd as From<File>>
>               <OwnedFd as From<TcpListener>>
>               <OwnedFd as From<TcpStream>>
>               <OwnedFd as From<UdpSocket>>
>               <OwnedFd as From<UnixDatagram>>
>               <OwnedFd as From<UnixListener>>
>               <OwnedFd as From<UnixStream>>
>               <OwnedFd as From<std::process::ChildStderr>>
>             and 2 others
>     = note: required for `Async<std::process::ChildStdin>` to implement `Into<OwnedFd>`
>     = note: required for `OwnedFd` to implement `TryFrom<Async<std::process::ChildStdin>>`
>     = note: required for `Async<std::process::ChildStdin>` to implement `TryInto<OwnedFd>`
> 
> error[E0599]: no method named `as_fd` found for struct `Async` in the current scope
>    --> /Users/usamaali/.cargo/registry/src/github.com-1ecc6299db9ec823/async-process-1.5.0/src/lib.rs:598:16
>     |
> 598 |         self.0.as_fd()
>     |                ^^^^^ method not found in `Async<std::process::ChildStdout>`
> 
> error[E0271]: type mismatch resolving `<OwnedFd as TryFrom<Async<std::process::ChildStdout>>>::Error == std::io::Error`
>    --> /Users/usamaali/.cargo/registry/src/github.com-1ecc6299db9ec823/async-process-1.5.0/src/lib.rs:607:17
>     |
> 607 |         value.0.try_into()
>     |                 ^^^^^^^^ expected enum `Infallible`, found struct `std::io::Error`
> 
> error[E0277]: the trait bound `OwnedFd: From<Async<std::process::ChildStdout>>` is not satisfied
>    --> /Users/usamaali/.cargo/registry/src/github.com-1ecc6299db9ec823/async-process-1.5.0/src/lib.rs:607:17
>     |
> 607 |         value.0.try_into()
>     |                 ^^^^^^^^ the trait `From<Async<std::process::ChildStdout>>` is not implemented for `OwnedFd`
>     |
>     = help: the following other types implement trait `From<T>`:
>               <OwnedFd as From<File>>
>               <OwnedFd as From<TcpListener>>
>               <OwnedFd as From<TcpStream>>
>               <OwnedFd as From<UdpSocket>>
>               <OwnedFd as From<UnixDatagram>>
>               <OwnedFd as From<UnixListener>>
>               <OwnedFd as From<UnixStream>>
>               <OwnedFd as From<std::process::ChildStderr>>
>             and 2 others
>     = note: required for `Async<std::process::ChildStdout>` to implement `Into<OwnedFd>`
>     = note: required for `OwnedFd` to implement `TryFrom<Async<std::process::ChildStdout>>`
>     = note: required for `Async<std::process::ChildStdout>` to implement `TryInto<OwnedFd>`
> 
> error[E0599]: no method named `as_fd` found for struct `Async` in the current scope
>    --> /Users/usamaali/.cargo/registry/src/github.com-1ecc6299db9ec823/async-process-1.5.0/src/lib.rs:671:16
>     |
> 671 |         self.0.as_fd()
>     |                ^^^^^ method not found in `Async<std::process::ChildStderr>`
> 
> error[E0271]: type mismatch resolving `<OwnedFd as TryFrom<Async<std::process::ChildStderr>>>::Error == std::io::Error`
>    --> /Users/usamaali/.cargo/registry/src/github.com-1ecc6299db9ec823/async-process-1.5.0/src/lib.rs:680:17
>     |
> 680 |         value.0.try_into()
>     |                 ^^^^^^^^ expected enum `Infallible`, found struct `std::io::Error`
> 
> error[E0277]: the trait bound `OwnedFd: From<Async<std::process::ChildStderr>>` is not satisfied
>    --> /Users/usamaali/.cargo/registry/src/github.com-1ecc6299db9ec823/async-process-1.5.0/src/lib.rs:680:17
>     |
> 680 |         value.0.try_into()
>     |                 ^^^^^^^^ the trait `From<Async<std::process::ChildStderr>>` is not implemented for `OwnedFd`
>     |
>     = help: the following other types implement trait `From<T>`:
>               <OwnedFd as From<File>>
>               <OwnedFd as From<TcpListener>>
>               <OwnedFd as From<TcpStream>>
>               <OwnedFd as From<UdpSocket>>
>               <OwnedFd as From<UnixDatagram>>
>               <OwnedFd as From<UnixListener>>
>               <OwnedFd as From<UnixStream>>
>               <OwnedFd as From<std::process::ChildStderr>>
>             and 2 others
>     = note: required for `Async<std::process::ChildStderr>` to implement `Into<OwnedFd>`
>     = note: required for `OwnedFd` to implement `TryFrom<Async<std::process::ChildStderr>>`
>     = note: required for `Async<std::process::ChildStderr>` to implement `TryInto<OwnedFd>`
> 
> Some errors have detailed explanations: E0271, E0277, E0599.
> For more information about an error, try `rustc --explain E0271`.
> error: could not compile `async-process` due to 9 previous errors`

I'm using following toolchain:
`rustup show`

```
Default host: x86_64-apple-darwin
rustup home:  /Users/<user>/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin
nightly-2022-09-14-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-apple-darwin

active toolchain
----------------

nightly-2022-09-14-x86_64-apple-darwin (default)
rustc 1.65.0-nightly (17cbdfd07 2022-09-13)
```

**Comment by kaichaosun** [comment]
Thanks for report, I need to update the dependencies to latest substrate.

**Comment by MoyunRz** [comment]
> I'm unable to build the master branch on macOS.
> 
> > `error[E0599]: no method named `as_fd`found for struct`Async`in the current scope --> /Users/usamaali/.cargo/registry/src/github.com-1ecc6299db9ec823/async-process-1.5.0/src/lib.rs:514:16 | 514 |         self.0.as_fd() |                ^^^^^ method not found in`Asyncstd::process::ChildStdin`
> > error[E0271]: type mismatch resolving `<OwnedFd as TryFrom<Async<std::process::ChildStdin>>>::Error == std::io::Error`
> > --> /Users/usamaali/.cargo/registry/src/github.com-1ecc6299db9ec823/async-process-1.5.0/src/lib.rs:523:17
> > |
> > 523 |         value.0.try_into()
> > |                 ^^^^^^^^ expected enum `Infallible`, found struct `std::io::Error`
> > error[E0277]: the trait bound `OwnedFd: From<Async<std::process::ChildStdin>>` is not satisfied
> > --> /Users/usamaali/.cargo/registry/src/github.com-1ecc6299db9ec823/async-process-1.5.0/src/lib.rs:523:17
> > |
> > 523 |         value.0.try_into()
> > |                 ^^^^^^^^ the trait `From<Async<std::process::ChildStdin>>` is not implemented for `OwnedFd`
> > |
> > = help: the following other types implement trait `From<T>`:
> > <OwnedFd as From>
> > <OwnedFd as From>
> > <OwnedFd as From>
> > <OwnedFd as From>
> > <OwnedFd as From>
> > <OwnedFd as From>
> > <OwnedFd as From>
> > <OwnedFd as Fromstd::process::ChildStderr>
> > and 2 others
> > = note: required for `Async<std::process::ChildStdin>` to implement `Into<OwnedFd>`
> > = note: required for `OwnedFd` to implement `TryFrom<Async<std::process::ChildStdin>>`
> > = note: required for `Async<std::process::ChildStdin>` to implement `TryInto<OwnedFd>`
> > error[E0599]: no method named `as_fd` found for struct `Async` in the current scope
> > --> /Users/usamaali/.cargo/registry/src/github.com-1ecc6299db9ec823/async-process-1.5.0/src/lib.rs:598:16
> > |
> > 598 |         self.0.as_fd()
> > |                ^^^^^ method not found in `Async<std::process::ChildStdout>`
> > error[E0271]: type mismatch resolving `<OwnedFd as TryFrom<Async<std::process::ChildStdout>>>::Error == std::io::Error`
> > --> /Users/usamaali/.cargo/registry/src/github.com-1ecc6299db9ec823/async-process-1.5.0/src/lib.rs:607:17
> > |
> > 607 |         value.0.try_into()
> > |                 ^^^^^^^^ expected enum `Infallible`, found struct `std::io::Error`
> > error[E0277]: the trait bound `OwnedFd: From<Async<std::process::ChildStdout>>` is not satisfied
> > --> /Users/usamaali/.cargo/registry/src/github.com-1ecc6299db9ec823/async-process-1.5.0/src/lib.rs:607:17
> > |
> > 607 |         value.0.try_into()
> > |                 ^^^^^^^^ the trait `From<Async<std::process::ChildStdout>>` is not implemented for `OwnedFd`
> > |
> > = help: the following other types implement trait `From<T>`:
> > <OwnedFd as From>
> > <OwnedFd as From>
> > <OwnedFd as From>
> > <OwnedFd as From>
> > <OwnedFd as From>
> > <OwnedFd as From>
> > <OwnedFd as From>
> > <OwnedFd as Fromstd::process::ChildStderr>
> > and 2 others
> > = note: required for `Async<std::process::ChildStdout>` to implement `Into<OwnedFd>`
> > = note: required for `OwnedFd` to implement `TryFrom<Async<std::process::ChildStdout>>`
> > = note: required for `Async<std::process::ChildStdout>` to implement `TryInto<OwnedFd>`
> > error[E0599]: no method named `as_fd` found for struct `Async` in the current scope
> > --> /Users/usamaali/.cargo/registry/src/github.com-1ecc6299db9ec823/async-process-1.5.0/src/lib.rs:671:16
> > |
> > 671 |         self.0.as_fd()
> > |                ^^^^^ method not found in `Async<std::process::ChildStderr>`
> > error[E0271]: type mismatch resolving `<OwnedFd as TryFrom<Async<std::process::ChildStderr>>>::Error == std::io::Error`
> > --> /Users/usamaali/.cargo/registry/src/github.com-1ecc6299db9ec823/async-process-1.5.0/src/lib.rs:680:17
> > |
> > 680 |         value.0.try_into()
> > |                 ^^^^^^^^ expected enum `Infallible`, found struct `std::io::Error`
> > error[E0277]: the trait bound `OwnedFd: From<Async<std::process::ChildStderr>>` is not satisfied
> > --> /Users/usamaali/.cargo/registry/src/github.com-1ecc6299db9ec823/async-process-1.5.0/src/lib.rs:680:17
> > |
> > 680 |         value.0.try_into()
> > |                 ^^^^^^^^ the trait `From<Async<std::process::ChildStderr>>` is not implemented for `OwnedFd`
> > |
> > = help: the following other types implement trait `From<T>`:
> > <OwnedFd as From>
> > <OwnedFd as From>
> > <OwnedFd as From>
> > <OwnedFd as From>
> > <OwnedFd as From>
> > <OwnedFd as From>
> > <OwnedFd as From>
> > <OwnedFd as Fromstd::process::ChildStderr>
> > and 2 others
> > = note: required for `Async<std::process::ChildStderr>` to implement `Into<OwnedFd>`
> > = note: required for `OwnedFd` to implement `TryFrom<Async<std::process::ChildStderr>>`
> > = note: required for `Async<std::process::ChildStderr>` to implement `TryInto<OwnedFd>`
> > Some errors have detailed explanations: E0271, E0277, E0599.
> > For more information about an error, try `rustc --explain E0271`.
> > error: could not compile `async-process` due to 9 previous errors`
> 
> I'm using following toolchain: `rustup show`
> 
> ```
> Default host: x86_64-apple-darwin
> rustup home:  /Users/<user>/.rustup
> 
> installed toolchains
> --------------------
> 
> stable-x86_64-apple-darwin
> nightly-2022-09-14-x86_64-apple-darwin (default)
> nightly-x86_64-apple-darwin
> 
> installed targets for active toolchain
> --------------------------------------
> 
> wasm32-unknown-unknown
> x86_64-apple-darwin
> 
> active toolchain
> ----------------
> 
> nightly-2022-09-14-x86_64-apple-darwin (default)
> rustc 1.65.0-nightly (17cbdfd07 2022-09-13)
> ```

I deleted the Cargo.lock file and re-do cargo build --release
rm -rf Cargo.lock & cargo build --release
