### ISSUE TITLE
Is it possible to start a substrate BABE blockchain with no Grandpa authorities and BABE validators?

### ISSUE THREAD

**Issue by stackphysics** [kaichaosun/substrate-stencil#15]
I'm trying to implement a PoS network on substrate using substrate provided pallets - pallet_session, pallet_staking, pallet_babe, etc. The current Runtime and chain spec implementation is similar to what is found in the [substrate repository](https://github.com/paritytech/substrate/tree/master/bin/node). I've realized that I need to set Session keys for GenesisConfig before starting the blockchain. I also noticed that the Session keys set for SessionConfig are used to configure the grandpa authorities.

My questions are:

Is there a way to start the blockchain such that no session keys are set?

Do all grandpa authorities need to be hardcoded in the chain spec? If not, how are the authorities added after nodes have gone live?

**Comment by kaichaosun** [comment]
> Is there a way to start the blockchain such that no session keys are set?

There is no other way to emit session keys from genesis as far as I know, but feel free to ask substrate stackoverflow since it has most devs active there.

> Do all grandpa authorities need to be hardcoded in the chain spec? If not, how are the authorities added after nodes have gone live?

Only genesis authorities needs to be hardcoded in chainspec, if you switch to PoS which means the validators are elected based on NPoS.
