### ISSUE TITLE
Stash does not have enough balance to bond.

### ISSUE THREAD

**Issue by WB-Expert5007** [kaichaosun/substrate-stencil#7]
Hi, I just cloned your project and build it.
When I run your node by this command, ```./target/release/substrate-stencil --dev```, it is getting this error.

```
Thread 'main' panicked at 'Stash does not have enough balance to bond.', /home/mersaid/.cargo/git/checkouts/substrate-7e08433d4c370a21/fc3fd07/frame/staking/src/pallet/mod.rs:561

This is a bug. Please report it at:

	support.anonymous.an

```
How can I solve this problem?

**Comment by kaichaosun** [comment]
I just run it, no such errors for me, please check if the code is latest or not.

**Comment by WB-Expert5007** [comment]
> I just run it, no such errors for me, please check if the code is latest or not.

Or How can I make only ```Alice``` account's balance  ```10,000,000,000``` and make balances of other accounts ```Zero```?

**Comment by kaichaosun** [comment]
You need to change chain_spec.rs file and do the changes, if you are not familiar with Substrate yet, better to follow the docs and tutorials first, check [here](https://docs.substrate.io/quick-start/), have a good learning day!

**Comment by WB-Expert5007** [comment]
> You need to change chain_spec.rs file and do the changes, if you are not familiar with Substrate yet, better to follow the docs and tutorials first, check [here](https://docs.substrate.io/quick-start/), have a good learning day!
Thanks very much for your advisor.
I have fixed error.
