### ISSUE TITLE
How can I add validators on your project?

### ISSUE THREAD

**Issue by WB-Expert5007** [kaichaosun/substrate-stencil#8]
Hi, I am going to add validators on your current project.
Did you do it already?
Or how can I do it?
Please help me.

**Comment by kaichaosun** [comment]
As I mentioned, if you just start with Substrate, you need to follow the docs and tutorials to get more familiar with Substrate and its pallets.
There will be a lot of requirements to setup a working blockchain, and I'm not available to support you in time. 
Enjoy your journey :)
