### ISSUE TITLE
How to add validators on POS node?

### ISSUE THREAD

**Issue by WB-Expert5007** [kaichaosun/substrate-stencil#9]
Hello, I have forked your current project and I am going to add validators now.
For that, I have researched this tutorial, https://docs.substrate.io/tutorials/get-started/trusted-network/.
As that guide, I have created new Keys and added it on ```customSpec.json```.
But it is getting this error now.

![image](https://user-images.githubusercontent.com/96474901/176563086-9ac29c13-9873-407a-8f0a-eefeddf2f4cd.png)

How can I solve this problem?
Please help me.

**Comment by ppoliani** [comment]
The error message gives you a hint I believe. You have an invalid json file. If authorities is supposed to be an array then you should use brackets `authorities: [...]`

**Comment by WB-Expert5007** [comment]
> The error message gives you a hint I believe. You have an invalid json file. If authorities is supposed to be an array then you should use brackets `authorities: [...]`

Hi, Thanks very much for your message.
I know that, But When I use the brackets ```authorities: [...]```, I have get other error.
Please check this.

![image](https://user-images.githubusercontent.com/96474901/177008780-c1e5b68c-81ef-4041-a07d-5497d52940cd.png)

One point, The consensus engine of My Current Node is POS, not POA.
And  In this tutorial, https://docs.substrate.io/tutorials/get-started/trusted-network/, this explain about adding new validators on POA consensus engine.

How can I add new validators on POS consensus engine?

Please teach me.

**Comment by kaichaosun** [comment]
It's similar to what Polkadot have its validator setup, https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot

**Comment by WB-Expert5007** [comment]
> 

Hello, I have followed that guide and added some validators like that.
Please check this.
![image](https://user-images.githubusercontent.com/96474901/177385954-2b93c958-d5b2-4c8d-a659-6dbb21f61347.png)

As you can see there, a lot of era time spent but all waiting validators doesn't active.
Why doesn't era change there?

How can I solve this problem?
How can I make era to change?
